### ISSUE TITLE
Doesn't work with Centos 7.2 and Check_MK 1.2.6

### ISSUE THREAD

**Issue by couilllard45682** [PagerDuty/pdagent-integrations#14]
Got the errors from notify.log while Nagios is trying to send a notification.

2016-08-10 05:01:53      executing /omd/sites/monitoring/local/share/check_mk/notifications/pagerduty-agent
2016-08-10 05:01:53 Output: Could not find platform independent libraries <prefix>
2016-08-10 05:01:53 Output: Could not find platform dependent libraries <exec_prefix>
2016-08-10 05:01:53 Output: Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
2016-08-10 05:01:53 Output: Traceback (most recent call last):
2016-08-10 05:01:53 Output:   File "/omd/sites/monitoring/lib/python/site.py", line 75, in <module>
2016-08-10 05:01:53 Output:     __boot()
2016-08-10 05:01:53 Output:   File "/omd/sites/monitoring/lib/python/site.py", line 3, in __boot
2016-08-10 05:01:53 Output:     import os
2016-08-10 05:01:53 Output: ImportError: No module named os
2016-08-10 05:01:53 Plugin exited with code 1

**Comment by divtxt** [comment]
@couilllard45682 - from the error messages, it looks like a broken or conflicting python setup.

Check that the OS python installation is ok by running the commands `which python`, `python --version`, and `/usr/bin/python --version`. Good output should look something like this:

```
~$ which python
/usr/bin/python
~$ python --version
Python 2.7.10
~$ /usr/bin/python --version
Python 2.7.10
```

You can also check that the pdagent install is working using the guide: https://www.pagerduty.com/docs/guides/agent-install-guide/ - use the sections "Verify the Agent is Running", and "Sending an Event to PagerDuty".

If those things look ok, you'll have to provide more details about how the OS & software setup on the host and also how you configured the Nagios integration.

**Comment by couilllard45682** [comment]
Yeah it seems there's a mismatch in version of Python in some way. They included their own Python binary and it's breaking stuff because of missing dependencies (as OS) in that version of Python.
I'm using the omd-daily package ( OMD - Open Monitoring Distribution Version 1.31.20160718)

[root@omd01 ~]#  which python
/bin/python
[root@omd01 ~]# python --version
Python 2.7.5
[root@omd01 ~]# /usr/bin/python --version
Python 2.7.5

OMD[monitoring]:~$ which python
~/bin/python
OMD[monitoring]:~$ ~/bin/python --version
Python 2.7.11
OMD[monitoring]:~$ /usr/bin/python --version
Python 2.7.11

The agent itself work well I can send manual alerts through CLI.

Any help much appreciated!

**Comment by divtxt** [comment]
Is that varying by user or is that before & after install?

Does `/usr/bin/python -c 'import os'` work? If so, try editing the `pagerduty_nagios.cfg` file and using an explicit python path in front of the `pd-nagios` commands:  e.g. `/usr/bin/python /usr/share/pdagent-integrations/bin/pd-nagios ...`

**Comment by couilllard45682** [comment]
Your command does work as root or another user than the one used for the OMD site (here it's 'monitoring')
So I've ended to allow the 'monitoring' user to use sudo as the 'pdagent' user for that command, without password, and adding sudo -u pdagent before the command line. It work as expected now! Thanks for the help!

**Comment by divtxt** [comment]
Awesome! Glad to help!
